name: build
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
    # Check out the repository under $GITHUB_WORKSPACE.
    - name: Checkout sigscape
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt install -y \
          libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libudev-dev \
          ninja-build

    - name: Build
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DMOCK_ADQAPI=ON -S .
          cmake --build build
          cmake --build build --target test/run_tests
        else
          cmake -B build -A x64 -DMOCK_ADQAPI=ON -S .
          cmake --build build --config Release
          cmake --build build --config Release --target test/run_tests
        fi
